CREATE TABLE [dbo].[Tags]
(
	[TagId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [ImageKey] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Tags_To_Images_Id] FOREIGN KEY (ImageKey) REFERENCES Images(Id)
)
